# Generated by Django 3.2.3 on 2021-05-14 22:31

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('PDU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
            preserve_default=False,
        ),
    ]
