# Generated by Django 3.2.3 on 2021-05-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDU', '0002_pdu_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='state',
            field=models.CharField(choices=[('In operation', 'In Operation'), ('Unavailable', 'Unavailable')], default='In operation', max_length=20),
        ),
    ]
